### ISSUE TITLE
Binned Likelihood Fits / Unfolding / Forward Folding

### ISSUE THREAD

**Issue by maxnoe** [zfit/zfit#172]
It would be nice for several usecases to support parameter and space vectors.

This would e.g. enable binned likelihood fits as e.g. used in unfolding or forward folding.
These are commonly situations were you have a vector of observed counts, let's call it `g` and a model dependent on some parameters that makes a prediction for said `g` and the model's parameters are then estimated by a Poissoinian Maximimum Likelihood fit.

```python
expected = A @ f
observed = g
Model = ProductModel([Poisson(e, o) for e, o in zip(expected, observed)]
```

Where `A` is a known migration matrix and `f` is either a vector of free parameters or calculated from a model with fewer parameters, e.g.  `f_i = func(i, *params)`

Is something like this worth considering? How would one go about implementing something like this?

**Comment by mayou36** [comment]
You're running into open doors here: I fully agree, internally we already play with [VectorSpace](https://github.com/zfit/zfit/blob/develop/zfit/core/sample.py#L58) and [MultiParameters](https://github.com/zfit/zfit/blob/develop/zfit/minimizers/minimizer_minuit.py#L81) (in fact, specifying a parameter with an array value and limits _should_ already work BUT don't use it yet): This is highly internal, ready to break any time. So I would highly discourage the use at its current stage.

Furthermore, binned fits are since quite a while in discussion (old thread https://github.com/zfit/zfit-development/issues/38 and new, but also not the newest thread https://github.com/zfit/zfit-development/issues/46), since we spend a lot of effort in the planing and design. The newest (and as it seems final) design has just been recently agreed on (internally), the specs will be put up soon (created a placeholder: https://github.com/zfit/zfit-development/issues/48). It will still take months until something is ready (just because it's not an experimental library but rather the stable python fitting library for HEP).

If you are interested in the design discussions (or even implementing something), you are very welcome and can start best here on GitHub (in the [development repo](https://github.com/zfit/zfit-development) (older threads are outdated maybe). In case you like the project and idea and _maybe_ (without any obligation!) like to contribute or be even part of it, we can also have a chat, just let us know!

**Comment by swertz** [comment]
> The newest (and as it seems final) design has just been recently agreed on (internally), the specs will be put up soon (created a placeholder: zfit/zfit-development#48). It will still take months until something is ready (just because it's not an experimental library but rather the stable python fitting library for HEP).

Does this mean there is an experimental branch somewhere that people could use to test things already?

**Comment by mayou36** [comment]
There is actually more then one, though with major changes in the next few weeks, so I will let you know as soon as it is "testable", that would be great if you could try it out asap

**Comment by swertz** [comment]
Sure, please do!

**Comment by MaxNoe** [comment]
Any news on this?

**Comment by mayou36** [comment]
Hey, thanks for asking back, however we are still in a working state, things got delayed.

Not to make false promises - I would rather not say a specific date - but we're having right now chats to publish some binned fits functionality, either in zfit or in a standalone repo to try out.

I will let you know, thanks again for pinging

**Comment by jonas-eschle** [comment]
Hi @maxnoe, we have the alpha version containing binned fits out, including poisson losses. [With PDFs](https://zfit.readthedocs.io/en/latest/user_api/zfit.pdf.html#binned-pdfs) and [different binned losses](https://zfit.readthedocs.io/en/latest/user_api/zfit.loss.html) including a [small introduction into binned PDFs](https://zfit-tutorials.readthedocs.io/en/latest/tutorials/components/30%20-%20Binned%20models.html).

It has to be installed with `--pre` as it is an alpha version. Let us know if you decide to give it a try and stumble upon problems and/or have any kind of feedback

**Comment by jonas-eschle** [comment]
Finally we released with 0.10 the possibility for binned fits, it can be installed simply with `pip install zfit`

**Comment by jonas-eschle** [comment]
Hi @maxnoe and @swertz , this has been fully implemented in zfit since a while, could you try it? Are there still things missing?

**Comment by swertz** [comment]
Hi @jonas-eschle , I have since left the field!
