### ISSUE TITLE
handling of unique names

### ISSUE THREAD

**Issue by niklasnolte** [zfit/zfit#186]
i guess you need to enforce unique names in the parameters, but can it be handled differently?
in a notebook, it's really annoying to see NameAlreadyTakenError's all over the place.
maybe fetch from a cache in case it was already defined (and give a warning)?

**Comment by mayou36** [comment]
We've come across this already a few times, and the big question is about how to handle it differently then? Because allowing to have the same name again would lead to confusions in the fit result. While automatically creating a new parameter with an individual name also does not really help in the fitresult.

I think it is mostly about the jupyter notebook again: it is in a state. And creating the same parameter again is something you "never" want to do in actual code. So while I agree that it is annoying, it seems to be an "inherent problem" of Jupyter.

The only alternative could be to return the existing parameter, which seems rather dangerous in real code (you will have a shared parameter without maybe noticing).

What I would recommend: restart the kernel and run all again. Or create the parameters just in one place. Or delete them (I think this should work).

Or do you have any other suggestion on how it should work best? What should be the behavior if you create a parameter that already exists? I agree it is suboptimal.

**Comment by niklasnolte** [comment]
i think the proposed alternative is quite nice. throw a warning when doing it, so people will know that the value is shared. i think nobody cares about warnings in jupyter, and as you said, in "real code" this won't happen anyway (and if it does, it rightly throws a warning)

**Comment by apuignav** [comment]
I'm not sure this works that well. We can fix variables, but in general a solution like Jupyter is not a good idea with TF, so this may end up failing on another side. The best solution is probably rerunning every time, but it's not a zfit thing, it's more a graph/TF issue, I believe.

**Comment by mayou36** [comment]
I agree with @apuignav, it is a more fundamental problem.

Let's put it that way: why do you ever need to recreate already existing objects in a Jupyter notebook? I know that it can convenient to "cheat" that way, but it is actually not what should happen.

Restarting the notebook does not work as an option for you?

For the proposed new behavior: it is simple to focus on one aspect, but I am still unsure about other points that need a consistent behavior as well:
 - should the old parameter be returned if you create one with the same name instead of a newly one created? (this is intentionally non-implemented behavior actually)
 - if not, we will just have two identical named parameters in the same fit maybe (which will break somewhere, e.g. minimizer, for sure)
 - "why" do we need this as a feature in the library? To allow a special case to happen?

My proposal: create a small wrapper function, something like "create_param" that creates you a parameter if it does not yet already exist (just keep track of the created names in a simple dict e.g.). And then either mutate the given name and create a new one or just return the already created one.

Few lines of code, your desired behavior. Python is just to beautiful for this small hacks :)

**Comment by marinang** [comment]
I do use a lot `zfit` with Jupiter notebooks, mostly to design a fit model, by testing different models and check rapidly the output but not to run a huge fit.

The fact you cannot rerun a cell where you already defined some parameter was annoying at the beginning but you get used to it. A small wrapper function as @mayou36 proposed is a very good solution I think.

**Comment by niklasnolte** [comment]
i did write a wrapper like this, but this is boilerplate that everyone will have to do.  
i do not like restarting the notebook because i load 30 gb of data into it.  
the cool thing about jupyter notebooks is exploration, so for instance when i want to develop a fit for the first time.

my usual progression is like this:
write a small model
fit
doesn't work? try other parameters or update the model (the model resides in one for smaller ones)
try again.

so now, every time i update the model (within the cell), i get this error.

maybe i am the only one who's annoyed by this enough to submit an issue, if so, it's a "special case". 

but, i mean, this error even appears in your tutorials, so we must agree that it is in fact annoying..
https://github.com/zfit/zfit-tutorials/blob/master/20%20-%20Composite%20Models.ipynb

**Comment by mayou36** [comment]
Thanks for pointing at the nobetook, this was due to a mistake in running, in does not actually happen, I forgot to update it.

> my usual progression is like this:
write a small model
fit
doesn't work? try other parameters or update the model (the model resides in one for smaller ones)
try again.

So why do "other parameters" have the same name? Do you maybe just want to update the current ones instead of creating new ones?

And: we are very happy in general to change the behavior if that improves things, but while it is always easy to look at one case, it is not so trivial to also be consistent with other cases. Or: what should the behavior be? If we find a consistent behavior, there is in principle nothing against the implementation of a new feature.

What should _exactly_ happen if you create a parameter with the same name. A warning is something, but what happens on the logical side?

 - should the old parameter be returned if you create one with the same name instead of a newly one created?
 - should the old parameter be deleted _together with any model that depends on it_ (this is an implication, otherwise objects would be ill-defined).
 - if not, we will just have two identical named parameters in the fit

Which feature could help in the future is maybe the https://github.com/zfit/zfit-development/issues/50, namescopes for parameters.

As much as I find it also kinda annoying myself (but I am also aware that this is "myself requesting impossible, logically ill-defined things") and would like to provide a better way, we need to first answer the questions above about the behavior before ever going further. As long as we don't find anything that basically _everyone_ can agree on, it's rather dangerous to put something like this into zfit.

You are right about the boilerplate, but how many lines of code? 3-4? Doable...
What can be done to remove the need for everyone to create it is to have an additional package, `zfit-notebook` or whatever, which contains this kind of helper functions, if it seems that there is a need for it. Or even just a web-page with "Jupyter Notebook: tips and tricks" that simply provides the source code for the function.

What do you think about the last paragraph @niklasnolte ?

**Comment by marinang** [comment]
> doesn't work? try other parameters or update the model (the model resides in one for smaller ones)
try again.

I think it is not ideal to define parameters and models in the same cell. Just define a bunch a parameters in a cell, or in a wrapper function. If you need another parameter add it in another cell right after.

Those parameters can be reused in any models, as many times as you want. 
The only cell you need to rerun is the cell where you define the likelihood.

**Comment by niklasnolte** [comment]
> So why do "other parameters" have the same name? Do you maybe just want to update the current ones instead of creating new ones?
They don't, its just that i rerun the cell where i defined my model.  
and @marinang, the cell being a logical unit i do not want to create a new cell every time i update something in my development iteration, since these parameters do not belong into a new cell, but go together with my signal model or whatever..

> What should _exactly_ happen if you create a parameter with the same name. A warning is something, but what happens on the logical side?
>     * should the old parameter be returned if you create one with the same name instead of a newly one created?
yes! and, if you find this unsafe, give a warning with it.

> You are right about the boilerplate, but how many lines of code? 3-4? Doable...
agreed, but annoying
> What can be done to remove the need for everyone to create it is to have an additional package, `zfit-notebook` or whatever, which contains this kind of helper functions, if it seems that there is a need for it. Or even just a web-page with "Jupyter Notebook: tips and tricks" that simply provides the source code for the function.
> What do you think about the last paragraph @niklasnolte ?
This is a good idea i'd say. So far, i have not needed other specific tricks for zfit with notebooks other than this wrapper (admittedly, i just started using it very recently). Are there more?

**Comment by mayou36** [comment]
> the cell being a logical unit i do not want to create a new cell every time i update something in my development iteration

True, but maybe you want to define finer grained logical units basically? At least that is what I often do, not just with zfit but also other libraries. But it's a style thing and I see the "one cell for model creating" logic of course, it makes sense.

> yes! and, if you find this unsafe, give a warning with it.

A warning can be overlooked. If you fit ~100 parameters or more and you, by accident, have two parameters with the same name, it is likely that is simply slips below the radar. It's also a certain design principle to make the parameters not retrievable by name in general and let the user through simple python deal with the bookkeeping (it's just too simple to write this things in Python, compared to e.g. C++). But I see the clear tension between simple Notebook exploration and 100+ param models in scripts...

> This is a good idea i'd say. So far, i have not needed other specific tricks for zfit with notebooks other than this wrapper (admittedly, i just started using it very recently). Are there more?

Not that I am aware of. But good! So I would propose to put it in the docs, are you familiar with RestructuredText? Do you may want to contribute the "Jupyter Notebooks: howto" or something similar?

The docs are currently restructured and WIP, so let's see where to put it structurally. If you're unfamiliar with contribution workflow, I can guide you through. What we need to startout is a PR with a file "jupyter_notebooks_howto.rst" with some text in there.

Do you wanna do that? You can also contact me directly in Gitter for example so I can guide you if you like.

**Comment by mayou36** [comment]
Hi @niklasnolte, just wondering what your thoughts are on that?

**Comment by niklasnolte** [comment]
hi @mayou36,
I do not want to contribute to this rn. just wanted to give the feedback. But a howto definitly looks like a good idea to me

**Comment by mayou36** [comment]
Just to properly resolve this, there is a section in the documentation that describes this and offers an alternative: https://zfit.readthedocs.io/en/latest/getting_started/intro/parameter.html#parameters-in-jupyter

Furthermore, there is an interesting discussion ongoing about this here: https://github.com/zfit/zfit/discussions/342
