### ISSUE TITLE
'ConstantParameter' object has no attribute 'set_value'

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#194]
It 's a bit unfortunate that one cannot change the value of `ConstantParameter`. Is there a particular reason?
I want parameters that are fixed/non floating in the minimisation with the possibility to change their values manually. I could use `Parameter` with `floating = False` but this is not what is returned when using 

```python
convert_to_parameter(value, name="name", prefer_floating=False)
```
.

**Comment by mayou36** [comment]
There is a reason: `ConstantParameter` is really just a constant, wrapped to have the correct API (maybe rename to 'Constant'?). (the deeper reason is efficiency for the variable creation. A `Parameter` always creates a `tf.Variable` below the scenes while a `ConstantParameter` does not. And a `tf.Variable` is needed to change the value of the parameter in every place). Therefore, the `ConstantParameter` should only be used if a real constant number is wanted.

What you want is a `Parameter` that is not floating.

But: the default behavior is to create `ConstantParameter` if a pure number is given (-> otherwise it gets again tricky with names. The idea is: parameters that you want to change have unique names. Others don't).

Changing the behavior of convert_to_parameter would in general produce too many `tf.Variable` I assume (I guess you even observed the slow behavior?).

Why do you actually use the `convert_to_parameter`?

But we can surely change the behavior or add even parameters to steer the conversion preference, e.g. "prefer_constant" or something like this.

**Comment by marinang** [comment]
> What you want is a Parameter that is not floating.

Actually for PR #179. In the `GaussianConstraint` for instance I set the observed value (`x`) of the parameter to constraint, that is a constant value obtained from another measurement, I use `convert_to_parameter` which convert the value to a `ConstantParameter`. 
When sampling the constraint I want to change the value of `x`.

**Comment by mayou36** [comment]
Hm, I see. Makes sense, yes. So we could add a `prefer_constant` flag? That is by default true? If False, this will always return a `Parameter` (or a `CompositeParameter` or similar).
Do you wanna add this directly in the PR with the corresponding logic?

**Comment by marinang** [comment]
I can add it in the PR yes.

**Comment by mayou36** [comment]
Or let me know if you have another solution in mind

**Comment by marinang** [comment]
In fact it doesn't look very nice to have both `prefer_constant` and `prefer_floating` flag in `convert_to_parameter` and seems to complicated. 
I would still replace `prefer_floating` by `prefer_constant` though and within the Constraint classes set the `floating` attribute of the created parameter to `False`.

**Comment by mayou36** [comment]
So `prefer_constant` returns either a floating Parameter or a (of course) fixed `ConstantParameter`? (if doable).
Sound fair!

**Comment by marinang** [comment]
Yeah basically:

``` python

def convert_to_parameter(value, ...):

    ...

    if doable:
        if prefer_constant:
            return ConstantParameter(...)
        else:
            return Parameter(...)
```

**Comment by mayou36** [comment]
yeah
