### ISSUE TITLE
Issue categories are not sufficient

### ISSUE THREAD

**Issue by HDembinski** [zfit/zfit#225]
When I click on "New Issue", I get four options. These options are not sufficient. How should I send a feature request, how give constructive criticism on zfit design? Constructive criticism on the design is not necessarily a bug, but it is also not a feature request.

Suggestions
* Add two new categories for "New issue": "Feature request" and "Other".
* Add an explanation/link for what is BehaviorUnderDiscussion

 At the bottom of these four options there is a tiny link to write a general issue, easily overlooked.

**Comment by mayou36** [comment]
Hi, thanks a lot for bringing this up; in fact, the "feature request" was not showing up due to a bug, but actually was there (duplicated, that made it hide).

I've fixed that, also added an "other" category and changed the description of the "BehaviorUnderDiscussion": it's an error that may be raised by the code.

Please feel free to close if you think it's resolved

**Comment by HDembinski** [comment]
Looks better now! 👍
