### ISSUE TITLE
Interpolation between multi-dimensional histograms/ parameters morphing

### ISSUE THREAD

**Issue by secholak** [zfit/zfit#238]
My analysis requires to scan over the various parameter values of the signal pdf. These parameters are extracted from the simulation and interpolated within the needed range. 

Is it planned to have a feature of the multi-dimensional interpolation of the entire pdf? For example, like the Moment morphing algorithm.

**Comment by marinang** [comment]
Just for completeness this is referring the algorithm described there https://doi.org/10.1016/j.nima.2014.10.033. @secholak is currently using my custom implementation https://gitlab.cern.ch/LHCb-QEE/llp2emunu_run2/-/blob/master/llp2emunu/Fit/LLP_signal_pdf/moment_morphing.py that I also used for my analysis but it would good to have a public implementation somewhere.

@mayou36 we discussed about it a while ago, you told me it would be make sense to add it in `zfit`. Do you know whether it should be implemented in `zfit` itself or in another subpackage?

**Comment by mayou36** [comment]
Thanks a lot for bringing this up, I see. As @marinang mentioned, it is surely a feature to be put there, but it is not the first priority currently. I think the larger priorities are more flexible models including conditional pdfs and proper binned models.

On the other hand, we usually prefer if something is first "hacky" or "specific for an analysis" implemented to be used in an analysis (and surely help with the implementation as far as possible) in order to discover limitations in the design and being able to better estimate what to put in finalized.

Is the current implementation you're using having limitations? Or what is your experience with it?

**Comment by secholak** [comment]
So far, there aren't problems from my side. @marinang did a great tool, but indeed it would be great to have it as a module.

**Comment by mayou36** [comment]
Of course, no doubt about that. We have more stuff also to add, shapes etc (@marinang) at some point, you would be very welcome (and it's highly appreciated) to help contributing. Anyway, if you find issues, have ideas on how to improve the usability, functionality, or even if it works out nicely, let us know; this kind of discussions and contributions are what drive this packages.
It could be a great contribution to zfit-physics btw, which is more specific for HEP and also has a lower barrier to contribute things.
