### ISSUE TITLE
Make ZfitParameter.value() a property

### ISSUE THREAD

**Issue by SebastianJL** [zfit/zfit#254]
All other getters on ZfitParameter are properties instead of methods.

**Comment by mayou36** [comment]
That's true, but it's rather better to move in the other direction, or have setter methods (to provide arguments). Two simple reasons why `value` should stay a method tough:
- consistency: value is always a method in other objects as well
- it's not just a property but can be a calculated property (e.g. composed parameter).

**Comment by SebastianJL** [comment]
I agree. Consistency in the whole api is much more valuable in this case.

I am interested though. Why do you think it is better to refactor properties into methods? Or what did you mean by "it's better to move in the other direction"?

**Comment by mayou36** [comment]
Yes, refactoring them as methods can be useful if arguments should be provided, mostly for the setter important. I think Parameters are fine, but it's easier to add arguments to methods then to setters (because in the later it's impossible). For forward compatiblity, I got rather rare on the property & setter usage (mostly setter).
