### ISSUE TITLE
Participate in iminuit v2.0 beta?

### ISSUE THREAD

**Issue by HDembinski** [zfit/zfit#278]
Dear zfit team,

I am about to finish a major rewrite of iminuit, version 2.0, that replaces Cython as the tool to wrap C++ Minuit2 with pybind11, which is going to solve several issues that the legacy code had. All the good things that this will bring are listed on top of this PR:
scikit-hep/iminuit#502

Switching to the new version of iminuit should be completely transparent to you, since the new version passes the comprehensive suite of unit tests of iminuit-v1.x. However, I would like to use this opportunity to finally remove interface that has been successively marked as deprecated in versions 1.3 to 1.5.

Therefore my two question to you:

 * Did you take note of the deprecation warnings in iminuit and did you keep up with the interface changes so far?
 * Are you interested in trying out a Beta release of v2.0 to work out any possible bugs in the new version before the release?

Best regards,
Hans, iminuit maintainer

**Comment by mayou36** [comment]
Hey, thanks for reaching out and we're surely up to help in the beta testing.

Yes, all deprecation warnings should be fixed on the `develop` version.

Let us know as soon as it is available.

**Comment by HDembinski** [comment]
Thank you! You can install install the beta from test.pypi:
`pip install -i https://test.pypi.org/simple/ iminuit`

**Comment by marinang** [comment]
I just tried quickly, and it seems that the object in [iminuit/util.py](https://github.com/scikit-hep/iminuit/blob/aa6e5783000f0a0845699c155801ab1650a19599/src/iminuit/util.py) are not subscriptable anymore ...

```python3
>>>result[0]["nfcn"]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a5ca215be958> in <module>
----> 1 result[0]["nfcn"]

TypeError: 'FMin' object is not subscriptable
```

same with `Param`.  We should now use `.nfcn` instead of `[nfcn]` apparently.

**Comment by mayou36** [comment]
yes, they all are attributes now (which is nicer tbh) and needs some refactoring from our side. I am on it in zfit.

**Comment by HDembinski** [comment]
Thank you for the feedback, I was wondering whether somebody still relies on `__getitem__` still, which was one of the things I forgot to deprecate. As discussed on gitter, I will prepare a transitional release 1.6 which deprecates all the remaining interface that will be removed in v2.0. Already adapting now does not hurt, though.

**Comment by mayou36** [comment]
So I've been testing and rewriting somewhat, however the removal of the `__getitem__` has some further consequences: it is implicitly an API definition and somewhat clashes with what we had with our custom implementation in zfit for the hessian and minos error (since it uses a dict).

But it raises the larger question. In zfit, we have:
- errors calculated and returned
- loss (cost) objects
- parameters
- minimizers

All with the idea to have the ideal API :P and we're trying to publish it in an [interface repository](https://github.com/zfit/zfit-interface) (currently a draft, need to push the newest APIs). However, we strive for the "best" API in this domains meaning we are very eager to discuss and incorporate any other input; in the end we don't want "the zfit API to be _the_ API" but we want to converge on the best API and use this. That's what zfit is mostly about.

Since iminuit also implements this things in one way or another and given your expertise in this domain @HDembinski , I think it would be very fruitful to have a specific discussion on this APIs.

We don't need to converge in everything of course, but not only is the input highly valued, we may can also change minor things _just to be more consistent in the HEP ecosystem overall_

**Comment by HDembinski** [comment]
@mayou36 Thank you for the invitation to discuss. It is certainly a topic about which I think regularly, so I am glad to be included. I had a quick look into the repo, but as everything in there is still empy and the link to the documentation leads nowhere, I don't know what to say at this point.

**Comment by mayou36** [comment]
We've put up some issues there in order to discuss: https://github.com/zfit/zfit-interface/issues/1

Maybe you do have some comments and ideas? I think a crucial point is the returned object, e.g. by only allowing attribute access via the dot operator but not via indexing, any similar minimizer has to mimic this

**Comment by HDembinski** [comment]
iminuit v2.0 is released, the breaking changes in the interface are documented in the [changelog](https://iminuit.readthedocs.io/en/stable/changelog.html) which can serve as an upgrade guide.

**Comment by HDembinski** [comment]
@mayou36 I will try to have a look at https://github.com/zfit/zfit-interface/issues/1

**Comment by mayou36** [comment]
Thanks for having a look at it! Regarding v2, we're still testing it and didn't yet fully convert.

What I stumpled upon: 
- giving kwargs to the initializer as done now raises an odd error, namely when doing:
```
iminuit.Minuit(func, start_values, grad=grad_func, error=errors)
```
raises
```
RuntimeError: positional arguments cannot be mixed with parameter keyword arguments {'error': [0.1, 0.0010000000474974513, 0.0010000000474974513]}
```
which is because I didn't use kwargs all along as it is not possible since `start_values` has to be positional only (correct?).

**Comment by HDembinski** [comment]
The error message is a bit misleading. It complains because the `error` keyword is no longer supported. Minuit guesses the step sizes now, so it is not necessary to specify them (although can still do that by assigning to Minuit.errors before running Minuit.migrad). The algorithm depends very little on those step sizes anyway.

**Comment by mayou36** [comment]
> Minuit guesses the step sizes now, so it is not necessary to specify them (although you can still do that by assigning to Minuit.errors before running Minuit.migrad). 

Great to hear!

> The algorithm depends very little on those step sizes anyway.

Yeaish, I found quite some cases where it depends somewhat on it, especially when e.g. doing an extended fit (yield around 10k-100k) and model parameters (order or 0.001). This was a problem sometimes for fits not to converge, so great!

I just wonder on the sigma vs cl though: since this is quite a change, is this something to adapt "throughout"? E.g. did we had a chat in the statistics group? (e.g. the ongoing p-value discussion)

**Comment by HDembinski** [comment]
> Yeaish, I found quite some cases where it depends somewhat on it, especially when e.g. doing an extended fit (yield around 10k-100k) and model parameters (order or 0.001). This was a problem sometimes for fits not to converge, so great!

Yes, that's a numerically problematic case. Ideally, the parameter values should be of similar scale, not differ by 7 orders in relative magnitude.

**Comment by HDembinski** [comment]
> I just wonder on the sigma vs cl though: since this is quite a change, is this something to adapt "throughout"? E.g. did we had a chat in the statistics group? (e.g. the ongoing p-value discussion)

Using sigma in the interface never made sense, cl is what you want. This is not related to the ongoing p-value discussion on the stat mailing list, these two topics are not related (the CL of a confidence interval is not a p-value).

**Comment by mayou36** [comment]
Having moved to iminuit v2 and all tests passing, I am gladly closing this. Many thanks @HDembinski for the advanced note on this
