### ISSUE TITLE
High Level User Helper functions

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#34]
We need functions that can add as "shortcuts" for repetitive functionality, placed under the `zfit` namespace. For example, "create nll, instantiate minimiser, minimise" -> `zfit.minimise`.

@rsilvaco Which extra shortcuts would we need?

# High Level User Helpers

## PDF related
 - pdf factory given a class
 - reset all variables to initial value (for repeated fits)

## Fit related
 - short-cut for build_nll->create_minimizer->fit
 - Likelihood scan
 - best_fit_value_out_of_n_fits

## General
 - eager execution: either use session internally OR no session at all (except where a session is *explicitly* needed, e.g. minimizer)

**Comment by rsilvaco** [comment]
@apuignav Here you are referring attributes of the nll specifically?

**Comment by apuignav** [comment]
No, I mean, sort of repetitive operations that could be packaged in neat functions if you don't want to do fancy things.

For example, for minimizing you don't need to create the NLL, instantiate the minimizer, and then run the minimization. This can be done in one step most of the time.

**Comment by rsilvaco** [comment]
Hum... slightly trick at this point to identify most of these functionalities. The likelihood scan is definitely one of the features. Let me try to brainstorm: 
* Likelihood scan: you have a fit result, and then you repeat the fit modifying and fixing one of this parameters. In this case the user should provide the the parameter to scan and at least the range for this parameter. The outcome should be the Delta NLL. 
* Best fit value: one feature that I think it is paramount and it is done really in a stupid manner in RooFit is the guarantee of have found the best fit value. I think we should have a function that repeats the fit nTimes (provided by the user) with initial random values and then the NLL and fit results are stored such that the user can examine it or even a simple return function with the best NLL value, the fraction of the time this solution has found and the separation to the next best NLL. Something like that. 
* Systematics studies have a plenty of them - but perhaps this is something to be discussed later, since it require the re-set of initial values and then repeating the fit with a slightly modified version.

**Comment by apuignav** [comment]
Where should we put this? in `highlevel.py`? I don't think it's a very clear name, and I would like them to be inside the `zfit` namespace anyway, but I would not like to put them in the `__init__.py`. What do you think? @rsilvaco Any nice file name for this? Or maybe we should put them in the module where they belong, such as `minimizer.py`, `loss.py` or an eventual `systematics.py`?

**Comment by rsilvaco** [comment]
Hum... naively I would say that they are indeed features of some of the functionalities of the fit, so I would suggest not to put in a high-level script. For instance, both likelihood scans and best fit value finder I think it should belong to the actual "fit algorithm". For instance, independent of the minimiser, the user should be able to ask for a scan or to repeat the fit nTimes the fit to verify the the best NLL has been found. Maybe the systematics itself should be indeed a separate systematics.py, but the first two I would put inside the general fitter.

**Comment by mayou36** [comment]
@apuignav so inside the zfit namespace means zfit.my_func? For not too many (say ~ 10) I would be for that (as @rsilvaco), given that this are user-friendly functions and they may should be in a "user-friendly"space. Otherwise, in the corresponding modules (`loss.py`, `pdf.py` etc.).

But the definition should not be put into the `__init.py__`, I agree, but that's not a problem. Internally, we can put them, I'd propose, into the corresponding modules.

**Comment by rsilvaco** [comment]
@mayou36 when you refer to "~10", you mean repetitions of the fit?

**Comment by mayou36** [comment]
No, sorry, the "~10" means the number of highlevel functions. Like `repeated_nll_fit`, `likelihood_scan` etc.(or ~20-30)

**Comment by rsilvaco** [comment]
Sure, this makes sense

**Comment by apuignav** [comment]
So, a first sloppy implementation for `minimize` which tells us things we need:

```python
def minimize(pdf, data, range_, params=None, minimizer='minuit', error_func=None):
    session = zfit.ztf.Session()  # TODO: Is session wrapped?
    with zfit.not_eager():
        with pdf.set_temp_range(range_):
            nll = zfit.unbinned_nll(pdf.prob(data))
            minimizer = zfit.minimize.get_minimizer(minimizer)(nll)  # TODO: Register minimizers
            if error_func:
                minimizer.set_error_method(error_func)  # TODO: add error options
            mini = minimizer.minimize(params)
            hesse = minimizer.hesse()
            error = minimizer.error(params)
        session.run([mini, hesse, error])
    return minimizer.get_state()  # Or, could we do, return session.run(minimizer.get_state())
```

This needs #35 and an option to register minimizers. Then, `get_minimizer` would be something like

```python
def get_minimizer(minimizer):
    if issubclass(minimizer, zfit.minimize.MinimizerBase):
        return minimizer
    elif isinstance(minimizer, str):
        return zfit.minimize.get_registered_minimizer(minimizer)
    else:
        raise Something
```

What do you think?

**Comment by mayou36** [comment]
Looks good!

`mini = minimizer.minimize(params)` needs a session and does the full minimization ->
`mini = minimizer.minimize(params, sess=sess)` (mini is then the state)

About `get_minimizer()`: What about a `get_default_minimizer` or similar? I would propose in general to just have the minimizers in the module, right?

so `minimizer = tf.minimize.MinuitMinimizer(params)` (or equivalently)

Or what's the advantage of a getter? (except: defining a default in only one place)

**Comment by apuignav** [comment]
My idea was to have something to get minimisers by name or by class. It was a sort of idea, but I think it can be done better indeed.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-development #29](https://github.com/zfit/zfit-development/issues/29) via [**ZenHub**](https://www.zenhub.com/)
