### ISSUE TITLE
Fitting range for outside of PDF

### ISSUE THREAD

**Issue by mzks** [zfit/zfit#375]
**Questions**
How can I fit with user-fitting range not including entire PDF, then visualize them?

I'm using zfit with developping its wrapper, mzfit.
For me, visualization of the fitting result is important.
I would like to plot data and fitting line at the same time.

In my naive thought, I can plot like this.
```
x_fit = np.arange(self.fit_lower, self.fit_upper, self.bin_width*0.01)
n_sample = len([d for d in self.data if self.fit_lower < d < self.fit_upper])
scale_factor = n_sample/self.fit_bins*self.obs.area()
y_fit = zfit.run(self.model.pdf(x_fit)*scale_factor)
```
https://github.com/mzks/mzfit/blob/98fe9a1700dc069c560b617697752bf0cc1c0dd5/mzfit/core.py#L153

n_sample is sample size including fitting range. Thus, PDF * n_sample should be on the data points.

However, when an entire PDF has not been included, (e.g., to remove noises on lower region), it doesn't works. Moreover, Fitting seems to be not also succeeded.

![image](https://user-images.githubusercontent.com/12980386/144572021-c91fbb67-9c12-4994-be9d-f8770d059bfe.png)
(I would like to fit the gaussian ~ 11, but remove ~5 peaks. Fitting range 8--25, in this case.)

**Comment by jonas-eschle** [comment]
Many thanks for bringing this up and that's a neat little wrapper you wrote!

So the PDF has a normalization range: this simply defines the normalization of the PDF and usually coincides with the range you want to fit in.
Then there is the "fitting range": this is a bit ill-defined, but it means the range in which _you evaluate the data points_ (and maybe also refers to the normalization range). If you want to only evaluate the points in a certain range, use a dataset that is only within a certain range (say use a space that is only within this range for the dataset).

So your plotting looks fine, but when you fit, you should use a dataset that _only_ contains the events that you want, say > 8

(and as a sidenote, I assume you use the newest zfit version? Otherwise it's recommended to upgrade)

How do you fit exactly?

**Comment by mzks** [comment]
Thank you very much for your quick reply.
In my wrapper, I use a dataset that only contains the event for fitting, but plot the entire dataset. 
That is, first, crop the data within fitting range. I fit the cropped data with zfit then, plot the original data and fitting function.

When we use the limited fitting range less than normalization range, how can we get the area (sample size) of the limited PDF?

**Comment by mzks** [comment]
My code is thought is there

```
import numpy as np
import matplotlib.pyplot as plt
import zfit
original_data = np.random.normal(1, 2, 100000)
data = original_data[original_data>0]
```
Then, we have a cropped data (with fit range).
![image](https://user-images.githubusercontent.com/12980386/144707301-647c6c71-22e3-4356-aef9-53f7b84045eb.png)

After fitting, how can we write the fitted model lines on the data?

**Comment by jonas-eschle** [comment]
Sorry for the late reply, this got lost!

> When we use the limited fitting range less than normalization range, how can we get the area (sample size) of the limited PDF?

I think you want to get the integral? Calling `integrate` takes two argument: the first are the limits and the second is the normalization. Usually, you want to provide just the first one.

If you're having an extended PDF, you can also use the `ext_integrate`, this will be the integral scaled by the yield

**Comment by jonas-eschle** [comment]
Did this solve your issue? If so, please close the question
