### ISSUE TITLE
Stats and other complicated functions

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#42]
We could include

- Profile likelihoods
- Confidence intervals (FC, F-test, whatever)
- Limit setting
- What else?

Out of all of these, maybe profile likelihoods make sense to be in `core` through a helper function (although I'm not 100% sure, depends how pure we want to be), but the others are more "examples" on how to use zfit, so I would suggest something like `zfit-stats` package which implements the `zfit.stats` namespace.

What do you think?

**Comment by apuignav** [comment]
So, coming back at this, should we have a stats module?

We could include sweights, Feldman cousins, etc.

**Comment by mayou36** [comment]
(overlooked, sorry)
Yes, I think so. It is needed and it belongs to the package (say `zfit.stats` namespace), otherwise it's quite incomplete.

Does it mix high (NLL profile) and low (conf intervals?) level functions then? We can of course, just not fully clear to me whether it's the best.

On limit setting, what do you mean exactly?

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #2](https://github.com/zfit/zfit-developement/issues/2) via [**ZenHub**](https://www.zenhub.com/)
