### ISSUE TITLE
iminuit required

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#51]
When using the `develop` branch, `iminuit` is required due to imports in `zfit/zfit/__init__.py`. Can we make this dynamical so that there is no error when importing `zfit` if iminuit is not installed? I guess we want to keep it as an optional dependency? Or should we force people to install it no matter what?

**Comment by mayou36** [comment]
For the moment being I would leave it as is, as anyone who wants to try it out uses iminuit, right? And the deps of iminuit are the usual python-scientific stack, so I think it's ok.

But later on we can still have a look at it whether it makes sense to include it or not. Let's see if anyone complains because of installation issues or similar.

**Comment by apuignav** [comment]
Yeah, I think it's not a big deal, but since iminuit requires some compilation, etc, I thought it was worth a discussion.

**Comment by mayou36** [comment]
yes agree! Let's see if anyone runs into troubles

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #25](https://github.com/zfit/zfit-developement/issues/25) via [**ZenHub**](https://www.zenhub.com/)
